baseURL = "https://seorankmyth.com"
disqusShortname = "educenter"
paginate = "6"
summaryLength = "10"
theme = "educenter-hugo"
themesDir = "../.."
title = "SEO Rank Myth"
[Languages.en]
contentDir = "content/english"
copyright = "&copy; 2020 seorankmyth.com - All rights reserved."
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
[[menu.main]]
name = "About"
URL = "about"
weight = 1
[[menu.main]]
name = "blog"
URL = "blog"
weight = 2
[[menu.main]]
name = "Contact"
URL = "contact"
weight = 3
[params]
address = ""
author = "SEO Rank Myth"
contact_form_action = "#"
description = "Providing SEO & content marketing services & tutorials for business owners and digital content creators."
email = "info@seorankmyth.com"
google_analitycs_id = ""
logo = "images/logo.png"
mobile = ""
top_header = true
[params.cookies]
enable = true
expire_days = 2
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = false
preloader = "images/preloader.gif"
[params.subscription]
enable = true
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
[[params.social]]
icon = "ti-facebook"
link = "https://facebook.com/seorankmyth"
title = "facebook"
[[params.social]]
icon = "ti-twitter-alt"
link = "https://twitter.com/seorankmyth"
title = "twitter"
[[params.social]]
icon = "ti-instagram"
link = "https://instagram.com/seorankmyth"
title = "instagram"
